title: Change Visibility
description: Change the access level of all documents in the current search view that you own. 
instructions: ''
type: object
documents:
  - query
  - selected
properties:
  access:
    title: Access level
    type: string
    default: private
    enum:
      - private
      - organization
      - public
required:
  - access
categories:
  - bulk
version: 2
