title: Change Visibility
description: This Add-On changes the access level of all documents (public, private, organization) in the current query. 
type: object
documents:
  - query
properties:
  access:
    title: Access level of the annotations (public, private, organization)
    type: string
    default: private
required:
  - access
categories:
  - bulk
version: 2
