title: Change Visibility
description: This Add-On changes the access level of all documents (public, private, organization) in the current query. 
instructions: ''
type: object
documents:
  - query
properties:
  access:
    title: Access level
    type: string
    default: private
    enum:
      - private
      - organization
      - public
required:
  - access
categories:
  - bulk
version: 2
