title: Change Visibility
description: This is an updated simple test add-on
type: object

documents:
  - query
properties:
  access:
    title: Access level of the annotations (public, private, organization)
    type: string
    default: private
required:
  - access
version: 2
